version: '3'

services:
  flagserver:
    container_name: ${CONTAINER_NAME:-flagserver}
    build: .
    ports:
      - "${FLAG_SERVER_PORT:-9999}:9999"
    restart: unless-stopped
    init: true
    read_only: true
    volumes:
      - ${FLAG_EXTERNAL_FILE_PATH:-./flag.txt}:${FLAG_SERVER_FILE_PATH:-/home/user/flag.txt}:ro
    environment:
      - FLAG_SERVER_PORT=${FLAG_SERVER_PORT:-9999}
      - FLAG_SERVER_FILE_PATH=${FLAG_SERVER_FILE_PATH:-/home/user/flag.txt}
      - FLAG_SERVER_HOST=${FLAG_SERVER_HOST:-0.0.0.0}
      - FLAG_SERVER_PROTOCOL=${FLAG_SERVER_PROTOCOL:-tcp}

