name: Deploy Images to GHCR

# env:
#   FLAG_FILE_PATH: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: './work-dir'
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: "Build Docker Image"
        run: |
          docker build . --tag ghcr.io/dominikborkowski/flagserver:latest
          # docker run ghcr.io/dominikborkowski/flagserver:latest
          docker push ghcr.io/dominikborkowski/flagserver:latest
